# Generated by Django 2.2.5 on 2019-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('T_PRN', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('years', models.CharField(max_length=20)),
                ('subjects', models.CharField(max_length=20)),
                ('adm_cat', models.CharField(max_length=50)),
                ('doj', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
                ('T_PRN', models.ManyToManyField(to='Home.Teacher')),
            ],
        ),
    ]
