# Generated by Django 2.2.5 on 2019-09-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='adm_cat',
        ),
    ]
