# Generated by Django 2.2.5 on 2019-09-13 15:08

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_teacher_adm_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='PRN',
            field=models.IntegerField(default=111111, verbose_name=dashboard.models.Student),
            preserve_default=False,
        ),
    ]
