# Generated by Django 2.2.5 on 2019-09-13 15:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20190913_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
