# Generated by Django 2.2.5 on 2019-09-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190912_0743'),
        ('Home', '0005_auto_20190913_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('status', models.BooleanField()),
                ('PRN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Student')),
            ],
        ),
    ]
