# Generated by Django 2.2.5 on 2019-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='PRN',
            field=models.IntegerField(),
        ),
    ]
