# Generated by Django 2.2.5 on 2019-09-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20190915_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='dob',
            field=models.CharField(default=-1994, max_length=50),
            preserve_default=False,
        ),
    ]
