# Generated by Django 2.2.5 on 2019-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('dname', models.ForeignKey(on_delete='models.CASCADE', to='UserApp.Depertment')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('dname', models.ForeignKey(on_delete='models.CASCADE', to='UserApp.Depertment')),
                ('student2', models.ManyToManyField(to='UserApp.Studs')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=100)),
                ('dname', models.ForeignKey(on_delete='models.CASCADE', to='UserApp.Depertment')),
                ('students', models.ManyToManyField(to='UserApp.Studs')),
            ],
        ),
    ]
