# Generated by Django 2.2.5 on 2019-09-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('PRN', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('adm_cat', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=10)),
            ],
        ),
    ]
