# Generated by Django 2.2.5 on 2019-09-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190908_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
